#!/usr/bin/env bash
#Prints numbers from 1-20 after no. 4 displays bad luck from china after no.9 displays bad luck from japan and no.17 displays bad luck from Italy.#
i="1"
while [ $i -le 20 ]
do 
	echo "$i"
	((i++))

case "$i" in

	5)
	echo "bad luck from China"
	;;

	10)
	echo "bad luck from Japan"
	;;

	18)
	echo "bad luck from Italy"
	;;
esac

done
